version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - ./backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build:
      context: ./backend
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
       - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./backend/.env
    networks:
      - app-network
    volumes:
      - ./backend:/app

# The frontend will not hot reload, but we can use docker to deploy it anyhow.
#  frontend:
#    build:
#      context: ./frontend
#    container_name: react-app
#    ports:
#      - "3000:3000"
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
