name: Code Quality and Lint

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install mypy pydantic black isort ruff
      - name: Run MyPy
        run: mypy --config-file ./backend/pyproject.toml ./backend
      - name: Run Black Check
        run: black backend --check --config=./backend/pyproject.toml
      - name: Run Isort Check
        run: isort --check-only backend --settings-path ./backend/pyproject.toml
      - name: Run Ruff Check
        run: ruff check backend --config ./backend/pyproject.toml
      - name: Run Frontend Code Quality Checks
        run: |
          cd frontend
          npm install
          if ! npx biome check ./src; then
            echo "Biome check failed for the frontend."
            exit 1
          fi
