name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: 654wak654/python-lint@1.5.0
      - name: Python Code Quality and Lint (Updated Fork)
        with:
          # A list of all paths to test
          python-root-list: "backend"
          # Use Pylint
          use-pylint: false
          # Use pycodestyle
          use-pycodestyle: false
          # Extra options: flake8 $(extra-flake8-options) $(python-root-list)
          extra-flake8-options: "--max-line-length 120"
          # Extra options: black --check $(extra-black-options) $(python-root-list)
          # extra-black-options: # optional, default is
          # Extra options: mypy $(extra-mypy-options) $(python-root-list)
          # extra-mypy-options: # optional, default is
          # Extra options: isort -rc $(extra-isort-options) $(python-root-list) -c --diff
          extra-isort-options: "--check-only"
