name: Python Code Quality and Lint

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install Dependencies"
        run: |
          pip install poetry
          cd backend
          poetry install
      - name: "Lint Code"
        run: |
          if ! ./backend/scripts/lint.sh; then
           echo "Linting failed."
           exit 1
          fi